### ISSUE TITLE
2023 Heatmap Empty

### ISSUE THREAD

**Issue by fonky415** [Richardsl/heatmap-calendar-obsidian#105]
Now that it's 2024, the heatmaps for 2023 and previous years are broken. Shows empty cells. How could I fix this?
<img width="741" alt="Screenshot 2024-01-01 at 2 04 37 PM" src="https://github.com/Richardsl/heatmap-calendar-obsidian/assets/112742453/0c375646-5c11-4562-9c09-90bcec7e2fe9">

**Comment by belaset** [comment]
Heatmap defaults to "current year" unless you specify otherwise, so you have to put 

`const calendarData = {
    year: 2023
}`

on your 2023 calendars and `year: 2024` on this year's.

**Comment by Vinfall** [comment]
Now I know why the generated heatmap has nothing but a `24` in the upper-left corner (it indicates the year) after wasting 50 minutes updating my templates without success then checking issue tracker and solving this within 30 seconds🤦🏼.

**Comment by fonky415** [comment]
Replacing it for me doesn't work...
<img width="491" alt="Screenshot 2024-01-03 at 11 22 00 PM" src="https://github.com/Richardsl/heatmap-calendar-obsidian/assets/112742453/3ac9d063-000e-4b50-bf18-c1d91cd314a8">

Where am I supposed to place the additional `year: 2024`? I put it here but it isn't working.

<img width="663" alt="Screenshot 2024-01-03 at 11 24 19 PM" src="https://github.com/Richardsl/heatmap-calendar-obsidian/assets/112742453/ba06b821-3773-4987-aa77-3838e1f3765a">

Thanks in advance.

**Comment by belaset** [comment]
You're close:

```
const calendarData = {
    year: 2024,
    intensityScaleStart: 1,
    intensityScaleEnd: 9,
    colors: { ... 
    ...the rest of your stuff here...
}
```

**Comment by fonky415** [comment]
Thank you so much!!! You're actually a savior. Have a great rest of your day

**Comment by belaset** [comment]
Happy to help :)
