### ISSUE TITLE
Help - Changing Folder

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [Richardsl/heatmap-calendar-obsidian#18]
Sorry I feel like I should be able to figure this out but apparently I really suck at this dataviewjs stuff. 
I'm just trying to point the dataviewjs to a different folder and nothing seems to be working. 
Can you help point a noob in the right direction?

![image](https://user-images.githubusercontent.com/96321415/172047286-cc5b3e55-d874-4e09-a4f1-ae1a99741176.png)

**Comment by Richardsl** [comment]
Might be a problem with the quotes. see this link https://blacksmithgu.github.io/obsidian-dataview/api/code-reference/#dvpagessource on the **dv.pages(source)** section
```"Note that folders need to be double-quoted inside the string (i.e., dv.pages("folder") does not work, but dv.pages('"folder"')"```

**Comment by Richardsl** [comment]
or try escaping the punctuation mark

**Comment by ObsidianTTRPGProject** [comment]
I've tried messing with those quite a bit. The calendar doesn't render if the double quotes are missing. I've also tried testing with a #tag instead of a folder but that also returns no results. I'm using the test code provided and really only looking to point it to a different folder. I wonder if my vault has anything to do with it. I have a very large vault and it's been known to cause issues with other plugins (database folder). 

![image](https://user-images.githubusercontent.com/96321415/172157467-ee60fa20-69f7-4e66-83ff-9bf2147d5fd1.png)

**Comment by ObsidianTTRPGProject** [comment]
Did some further testing. Can get the code working on a different vault. Fails to pick up the data in my primary vault. My primary vault is rather large though and since I've seen similar issues with dataviewjs queries in my vault I'm starting to think the issue may be with the dataview plugin struggling.

**Comment by ObsidianTTRPGProject** [comment]
Tonight everything just seems to be working. I can't explain it.
