### ISSUE TITLE
Heatmap not rendering

### ISSUE THREAD

**Issue by kanziekan** [Richardsl/heatmap-calendar-obsidian#32]
I've been having issues getting the heatmap plugin to work. My daily notes are in the date format: YYYY-MM-DD so I'm confused as to why it's not working

![image](https://user-images.githubusercontent.com/65224761/181592170-0b017e64-2ecc-4cfc-ac5b-5357a3e2a49d.png)

Nothing shows. I use a Windows 10 computer.

![image](https://user-images.githubusercontent.com/65224761/181592249-948cd7ff-b97f-45e0-a8d9-1f561f52ec32.png)

**Comment by E1phiph0ros** [comment]
same problem. Have you figured out how to do this? Mine is always showing a full-year blank graph..

**Comment by Richardsl** [comment]
what operating system are you on? can you console.log the results of dv.pages?

**Comment by Richardsl** [comment]
also, do you have the latest version of both obsidian and heatmap?

**Comment by kanziekan** [comment]
> same problem. Have you figured out how to do this? Mine is always showing a full-year blank graph..

Unfortunately I haven't, it's a shame there is hardly any support for this plugin. :/

**Comment by kanziekan** [comment]
> what operating system are you guys using? can you console.log the results of dv.pages?

I use Windows 10 and I'm not sure how to do that, I'm not very strong with coding.



> also, do you have the latest version of both obsidian and heatmap?

Yes I do have the latest version of both

**Comment by Richardsl** [comment]
Please try adding a dv.pagraph to your code like below, and check if it prints out anything
```js
for(let page of dv.pages('"#-Journal"').where(p=>p.mood)){
	dv.paragraph(page.file.name + " Mood: " + page.mood) 
        calendarData.entries.push({
            date: page.file.name,
            intensity: page.mood,
    })  
}
```

**Comment by kanziekan** [comment]
![image](https://user-images.githubusercontent.com/65224761/182048367-a0904e3f-dd4c-4b4a-bd59-0ddda7dff679.png)
![image](https://user-images.githubusercontent.com/65224761/182048369-ec8d9901-3529-4737-8a92-4bb33ad27238.png)
It unfortunately still doesn't change anything. Maybe there is something in my settings? I've enabled Javascript Queries for Dateview.

**Comment by Azurewren** [comment]
I experienced this issue too. I fixed it by changing `'"#-Journal"'` section to `'#-Journal'`. Basically removed the double quotes from around the hash-tag.

**Comment by kanziekan** [comment]
> I experienced this issue too. I fixed it by changing `'"#-Journal"'` section to `'#-Journal'`. Basically removed the double quotes from around the hash-tag.

That alone didn't work for me...
![image](https://user-images.githubusercontent.com/65224761/182843612-244d1843-3101-4ee4-83fb-73dd5410724a.png)
 
BUT I figured out the problem, it had to do with the emoji I was using.
![image](https://user-images.githubusercontent.com/65224761/182844138-15949f0c-4b62-4a47-988d-f6306b6ba80e.png)
![image](https://user-images.githubusercontent.com/65224761/182844270-e034e445-eeac-4227-8e0e-a8e44a217dd5.png)
