### ISSUE TITLE
Hover Preview - Unexpected Result

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [Richardsl/heatmap-calendar-obsidian#34]
Does anyone know why I am getting this result with the new Hover Preview?

**CODE:**
```dataviewjs

dv.span("**💀🧙‍♂️🧙‍♀️ D&D Session 🧙‍♀️🧙‍♂️💀**")

const calendarData = {
    colors: {
        blue: ["#ffdf04","#ffbe04","#ff9a03","#ff6d02","#ff2c01"]
    },
    entries: [],
    showCurrentDayBorder: false
}

for(let page of dv.pages('"0. Session Journals/Deadly Depth Inn"').where(p=>p.players)){
    calendarData.entries.push({
        date: page.sessionDate, // (required) Format YYYY-MM-DD
        intensity: page.players,
        content: await dv.span(`[](${page.file.name})`), //for hover preview
    })  
}

renderHeatmapCalendar(this.container, calendarData)

```

**RESULT:**
Each box is displaying the title of the Note instead of nothing and the mouse over does not work. 
![image](https://user-images.githubusercontent.com/96321415/183233110-6e8bdf70-1c69-4661-bc58-cb40e2c99d6f.png)

**NOTE FRONT MATTER**
```
---
sessionDate: 2022-02-06
players: 6
type: Session Journal
---
```

**Comment by ObsidianTTRPGProject** [comment]
Resolved: File has to be named: dd-mm-yyyy

**Comment by Richardsl** [comment]
Really? **YYYY-MM-DD** doesn't work?

**Comment by ObsidianTTRPGProject** [comment]
I had a description in my heading also.

dd-mm-yyyy <random text>

It didn't like the <random text>
