### ISSUE TITLE
Hover preview is not working with file names that contain a space character

### ISSUE THREAD

**Issue by vadimtrifonov** [Richardsl/heatmap-calendar-obsidian#42]
Here is the part of my script where I setup the hover preview:
```js
...
data.entries.push(
    {
        date: page.started,
        intensity: 1,
        content: await dv.span(`[](${page.file.name})`) // not working as expected
    }
)
...
```

Here is the result with a file named `Europe`:

<img width="879" alt="Screen Shot 2022-09-23 at 17 55 29" src="https://user-images.githubusercontent.com/1075070/191915595-e30dd921-88ee-4445-b5d8-2db9b2df9091.png">

Here is the result with a file named `Europe Test`:

<img width="772" alt="Screen Shot 2022-09-23 at 17 57 47" src="https://user-images.githubusercontent.com/1075070/191915928-348325fb-c594-41d0-a873-f584aedcbb66.png">

Splitting the file name by a space character solves the rendering issue, but, naturally, prevents the Heatmap from displaying the file contents.

```js
await dv.span(`[](${page.file.name.split(" ")["0"]})`)
```

<img width="847" alt="Screen Shot 2022-09-23 at 18 00 23" src="https://user-images.githubusercontent.com/1075070/191916375-e345c403-397c-4be4-a414-6a31ae0f8d48.png">

**Comment by Richardsl** [comment]
The plugin was really just intended for daily notes with the title format YYYY-MM-DD.
Maybe you could modify the code used in this issue: https://github.com/Richardsl/heatmap-calendar-obsidian/discussions/2

**Comment by Richardsl** [comment]
or possibly this solution from another issue:  <img alt="image" width="684" src="https://user-images.githubusercontent.com/25422645/191842766-d749b81a-e40b-4daa-b4ec-0791549693fe.png">
