### ISSUE TITLE
Current day border not showing after the latest update

### ISSUE THREAD

**Issue by cakechaser** [Richardsl/heatmap-calendar-obsidian#63]
After the latest update the showCurrentDayBorder property is not working correctly.
Even if it's set to true, the border is not rendered on the heatmap.

<img width="338" alt="image" src="https://user-images.githubusercontent.com/16690476/212285426-c4e2ae43-266a-4d56-8a83-aed4211dfcfe.png">
<img width="368" alt="image" src="https://user-images.githubusercontent.com/16690476/212285487-b9b8673c-7d0b-4678-92eb-d8342bf8ba93.png">

**Comment by jkj-jim** [comment]
+1
