### ISSUE TITLE
Dark mode stopped working for empty cells

### ISSUE THREAD

**Issue by PeterBeckley** [Richardsl/heatmap-calendar-obsidian#64]
Class "isEmpty" isn't getting added to the ```<li>```s, so those cells have the same color regardless of light or dark mode. Text elements properly switch between modes, just not the empty cells. EDIT: no class names are getting pushed. "today" is missing as well.

**Comment by PeterBeckley** [comment]
Yes, sorry for not adding that.

**Comment by bakharew** [comment]
Same problem, just installed the plugin

**Comment by afterglowu** [comment]
In commit 649a7fd638937bace97dbd16196f1355b707fee8, file `main.ts`, the code

```typescript
const box: Box = {
    classNames: [],
}
```

was replaced with

```typescript
const box: Box = {}
```

So the following operations won't push the classes (`today`, `hasData` and `isEmpty`) into `box.classNames` as we expected, thus cause this issue and #63.

```typescript
// main.ts
box.classNames?.push("today")
box.classNames?.push("hasData")
box.classNames?.push("isEmpty")
```
